export const currencies = [
  // --- 15 devises mondiales les plus utilisées ---
  { code: 'USD', name: 'Dollar américain', symbol: '$' },
  { code: 'EUR', name: 'Euro', symbol: '€' },
  { code: 'JPY', name: 'Yen japonais', symbol: '¥' },
  { code: 'GBP', name: 'Livre sterling', symbol: '£' },
  { code: 'CHF', name: 'Franc suisse', symbol: 'CHF' },
  { code: 'CAD', name: 'Dollar canadien', symbol: '$' },
  { code: 'AUD', name: 'Dollar australien', symbol: '$' },
  { code: 'CNY', name: 'Yuan chinois', symbol: '¥' },
  { code: 'INR', name: 'Roupie indienne', symbol: '₹' },
  { code: 'BRL', name: 'Real brésilien', symbol: 'R$' },
  { code: 'RUB', name: 'Rouble russe', symbol: '₽' },
  { code: 'MXN', name: 'Peso mexicain', symbol: '$' },
  { code: 'SGD', name: 'Dollar de Singapour', symbol: '$' },
  { code: 'HKD', name: 'Dollar de Hong Kong', symbol: '$' },
  { code: 'KRW', name: 'Won sud-coréen', symbol: '₩' },

  // --- Devises africaines les plus utilisées ---
  { code: 'ZAR', name: 'Rand sud-africain', symbol: 'R' },
  { code: 'NGN', name: 'Naira nigérian', symbol: '₦' },
  { code: 'EGP', name: 'Livre égyptienne', symbol: '£' },
  { code: 'KES', name: 'Shilling kényan', symbol: 'Sh' },
  { code: 'GHS', name: 'Cedi ghanéen', symbol: '₵' },
  { code: 'MAD', name: 'Dirham marocain', symbol: 'د.م' },
  { code: 'DZD', name: 'Dinar algérien', symbol: 'دج' },
  { code: 'TND', name: 'Dinar tunisien', symbol: 'د.ت' },
  { code: 'UGX', name: 'Shilling ougandais', symbol: 'Sh' },
  { code: 'TZS', name: 'Shilling tanzanien', symbol: 'Sh' },
  { code: 'XOF', name: 'Franc CFA BCEAO', symbol: 'Fr' },
  { code: 'XAF', name: 'Franc CFA BEAC', symbol: 'Fr' },
  { code: 'ETB', name: 'Birr éthiopien', symbol: 'Br' },
  { code: 'BWP', name: 'Pula botswanais', symbol: 'P' },
  { code: 'MUR', name: 'Roupie mauricienne', symbol: '₨' },
  { code: 'SCR', name: 'Roupie seychelloise', symbol: '₨' },
  { code: 'CDF', name: 'Franc congolais', symbol: 'FC' },
  { code: 'GNF', name: 'Franc guinéen', symbol: 'FG' },
  { code: 'GMD', name: 'Dalasi gambien', symbol: 'D' },
  { code: 'BIF', name: 'Franc burundais', symbol: 'FBu' },
  { code: 'DJF', name: 'Franc djiboutien', symbol: 'Fdj' },
  { code: 'RWF', name: 'Franc rwandais', symbol: 'FRw' },
  { code: 'LSL', name: 'Loti (Lesotho)', symbol: 'L' },
  { code: 'AOA', name: 'Kwanza angolais', symbol: 'Kz' },
  { code: 'MWK', name: 'Kwacha malawite', symbol: 'MK' },
]
