-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.agencies (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name character varying NOT NULL UNIQUE,
  description text,
  address text,
  logo_url text,
  contact_email character varying,
  contact_phone character varying,
  website character varying,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid,
  deleted_at timestamp with time zone,
  CONSTRAINT agencies_pkey PRIMARY KEY (id),
  CONSTRAINT agencies_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.attachments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  agency_id uuid NOT NULL,
  attachable_type character varying NOT NULL,
  attachable_id uuid NOT NULL,
  name character varying NOT NULL,
  file_url text NOT NULL,
  file_type character varying,
  file_size integer,
  description text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid,
  deleted_at timestamp with time zone,
  CONSTRAINT attachments_pkey PRIMARY KEY (id),
  CONSTRAINT attachments_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id),
  CONSTRAINT attachments_agency_id_fkey FOREIGN KEY (agency_id) REFERENCES public.agencies(id)
);
CREATE TABLE public.checklist_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  agency_id uuid NOT NULL,
  checklist_id uuid NOT NULL,
  name character varying NOT NULL,
  verified boolean NOT NULL DEFAULT false,
  comment text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid,
  CONSTRAINT checklist_items_pkey PRIMARY KEY (id),
  CONSTRAINT checklist_items_checklist_id_fkey FOREIGN KEY (checklist_id) REFERENCES public.checklists(id),
  CONSTRAINT checklist_items_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id),
  CONSTRAINT checklist_items_agency_id_fkey FOREIGN KEY (agency_id) REFERENCES public.agencies(id)
);
CREATE TABLE public.checklists (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  agency_id uuid NOT NULL,
  vehicle_id uuid NOT NULL,
  date timestamp with time zone NOT NULL DEFAULT now(),
  inspector character varying NOT NULL,
  comments text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid,
  deleted_at timestamp with time zone,
  CONSTRAINT checklists_pkey PRIMARY KEY (id),
  CONSTRAINT checklists_agency_id_fkey FOREIGN KEY (agency_id) REFERENCES public.agencies(id),
  CONSTRAINT checklists_vehicle_id_fkey FOREIGN KEY (vehicle_id) REFERENCES public.vehicles(id),
  CONSTRAINT checklists_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.drivers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  agency_id uuid NOT NULL,
  full_name character varying NOT NULL,
  photo_url text,
  birth_date date,
  birth_place character varying,
  address text,
  phone character varying,
  email character varying,
  id_number character varying,
  license_number character varying,
  license_category character varying,
  license_issue_date date,
  license_expiry_date date,
  document_scans text,
  hire_date date,
  status character varying CHECK (status::text = ANY (ARRAY['active'::character varying, 'on_leave'::character varying, 'suspended'::character varying, 'inactive'::character varying]::text[])),
  contract_type character varying,
  assigned_area character varying,
  daily_salary numeric,
  monthly_salary numeric,
  commission_percentage numeric,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid,
  deleted_at timestamp with time zone,
  CONSTRAINT drivers_pkey PRIMARY KEY (id),
  CONSTRAINT drivers_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id),
  CONSTRAINT drivers_agency_id_fkey FOREIGN KEY (agency_id) REFERENCES public.agencies(id)
);
CREATE TABLE public.maintenances (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  agency_id uuid NOT NULL,
  vehicle_id uuid NOT NULL,
  type character varying CHECK (type::text = ANY (ARRAY['Revision'::character varying, 'Oil_change'::character varying, 'Tires'::character varying, 'Brakes'::character varying, 'Other'::character varying]::text[])),
  description text,
  scheduled_date timestamp with time zone NOT NULL,
  completion_date timestamp with time zone,
  status character varying CHECK (status::text = ANY (ARRAY['Scheduled'::character varying, 'In_progress'::character varying, 'Completed'::character varying, 'Cancelled'::character varying]::text[])),
  cost numeric,
  garage character varying,
  mileage_at_service integer,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid,
  deleted_at timestamp with time zone,
  CONSTRAINT maintenances_pkey PRIMARY KEY (id),
  CONSTRAINT maintenances_agency_id_fkey FOREIGN KEY (agency_id) REFERENCES public.agencies(id),
  CONSTRAINT maintenances_vehicle_id_fkey FOREIGN KEY (vehicle_id) REFERENCES public.vehicles(id),
  CONSTRAINT maintenances_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.memberships (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  agency_id uuid NOT NULL,
  role character varying NOT NULL CHECK (role::text = ANY (ARRAY['admin'::character varying, 'chauffeur'::character varying, 'controleur'::character varying, 'gestionnaire'::character varying]::text[])),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid,
  deleted_at timestamp with time zone,
  CONSTRAINT memberships_pkey PRIMARY KEY (id),
  CONSTRAINT memberships_agency_id_fkey FOREIGN KEY (agency_id) REFERENCES public.agencies(id),
  CONSTRAINT memberships_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT memberships_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.parking_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  agency_id uuid NOT NULL,
  vehicle_id uuid NOT NULL,
  entry_date timestamp with time zone NOT NULL DEFAULT now(),
  exit_date timestamp with time zone,
  expiry_date timestamp with time zone NOT NULL,
  spot character varying NOT NULL,
  driver character varying NOT NULL,
  destination text,
  entry_mileage integer,
  exit_mileage integer,
  comments text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid,
  deleted_at timestamp with time zone,
  CONSTRAINT parking_logs_pkey PRIMARY KEY (id),
  CONSTRAINT parking_logs_agency_id_fkey FOREIGN KEY (agency_id) REFERENCES public.agencies(id),
  CONSTRAINT parking_logs_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id),
  CONSTRAINT parking_logs_vehicle_id_fkey FOREIGN KEY (vehicle_id) REFERENCES public.vehicles(id)
);
CREATE TABLE public.payments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  agency_id uuid NOT NULL,
  driver_id uuid NOT NULL,
  payment_type character varying CHECK (payment_type::text = ANY (ARRAY['Salary'::character varying, 'Bonus'::character varying, 'Advance'::character varying, 'Reimbursement'::character varying, 'Other'::character varying]::text[])),
  amount numeric NOT NULL,
  payment_date timestamp with time zone NOT NULL DEFAULT now(),
  payment_method character varying CHECK (payment_method::text = ANY (ARRAY['Cash'::character varying, 'Mobile_money'::character varying, 'Bank_transfer'::character varying, 'Check'::character varying, 'Other'::character varying]::text[])),
  transaction_reference character varying,
  payment_period character varying,
  comments text,
  status character varying NOT NULL CHECK (status::text = ANY (ARRAY['Completed'::character varying, 'Pending'::character varying, 'Cancelled'::character varying]::text[])),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid,
  deleted_at timestamp with time zone,
  CONSTRAINT payments_pkey PRIMARY KEY (id),
  CONSTRAINT payments_agency_id_fkey FOREIGN KEY (agency_id) REFERENCES public.agencies(id),
  CONSTRAINT payments_driver_id_fkey FOREIGN KEY (driver_id) REFERENCES public.drivers(id),
  CONSTRAINT payments_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.revenues (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  agency_id uuid NOT NULL,
  vehicle_id uuid NOT NULL,
  driver_id uuid,
  date timestamp with time zone NOT NULL DEFAULT now(),
  amount numeric NOT NULL,
  payment_method character varying CHECK (payment_method::text = ANY (ARRAY['Cash'::character varying, 'Mobile_money'::character varying, 'Bank_transfer'::character varying, 'Other'::character varying]::text[])),
  comments text,
  proof_url text,
  entry_time time without time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid,
  deleted_at timestamp with time zone,
  CONSTRAINT revenues_pkey PRIMARY KEY (id),
  CONSTRAINT revenues_agency_id_fkey FOREIGN KEY (agency_id) REFERENCES public.agencies(id),
  CONSTRAINT revenues_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id),
  CONSTRAINT revenues_driver_id_fkey FOREIGN KEY (driver_id) REFERENCES public.drivers(id),
  CONSTRAINT revenues_vehicle_id_fkey FOREIGN KEY (vehicle_id) REFERENCES public.vehicles(id)
);
CREATE TABLE public.settings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  agency_id uuid NOT NULL,
  key character varying NOT NULL,
  value text,
  data_type character varying NOT NULL DEFAULT 'string'::character varying,
  description text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid,
  CONSTRAINT settings_pkey PRIMARY KEY (id),
  CONSTRAINT settings_agency_id_fkey FOREIGN KEY (agency_id) REFERENCES public.agencies(id),
  CONSTRAINT settings_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.trash (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  agency_id uuid NOT NULL,
  trashable_type character varying NOT NULL,
  trashable_id uuid NOT NULL,
  trashable_data jsonb NOT NULL,
  deleted_at timestamp with time zone NOT NULL DEFAULT now(),
  deleted_by uuid,
  restore_data jsonb,
  restored_at timestamp with time zone,
  restored_by uuid,
  permanent_delete_at timestamp with time zone,
  CONSTRAINT trash_pkey PRIMARY KEY (id),
  CONSTRAINT trash_deleted_by_fkey FOREIGN KEY (deleted_by) REFERENCES auth.users(id),
  CONSTRAINT trash_restored_by_fkey FOREIGN KEY (restored_by) REFERENCES auth.users(id),
  CONSTRAINT trash_agency_id_fkey FOREIGN KEY (agency_id) REFERENCES public.agencies(id)
);
CREATE TABLE public.users (
  id uuid NOT NULL,
  first_name character varying,
  last_name character varying,
  display_name character varying,
  avatar_url text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  last_sign_in_at timestamp with time zone,
  deleted_at timestamp with time zone,
  CONSTRAINT users_pkey PRIMARY KEY (id),
  CONSTRAINT users_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id)
);
CREATE TABLE public.vehicles (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  agency_id uuid NOT NULL,
  plate_number character varying NOT NULL,
  brand character varying NOT NULL,
  model character varying NOT NULL,
  year integer,
  type character varying CHECK (type::text = ANY (ARRAY['Car'::character varying, 'Truck'::character varying, 'Utility'::character varying, 'Motorcycle'::character varying]::text[])),
  status character varying CHECK (status::text = ANY (ARRAY['Available'::character varying, 'In_service'::character varying, 'Maintenance'::character varying, 'Out_of_service'::character varying, 'Reserved'::character varying]::text[])),
  color character varying,
  vin character varying,
  service_assignment character varying,
  driver_id uuid,
  fuel_type character varying CHECK (fuel_type::text = ANY (ARRAY['Gasoline'::character varying, 'Diesel'::character varying, 'Electric'::character varying, 'Hybrid'::character varying]::text[])),
  mileage integer NOT NULL DEFAULT 0,
  service_start_date timestamp with time zone,
  passenger_capacity integer,
  load_capacity numeric,
  condition character varying,
  description text,
  next_technical_control timestamp with time zone,
  next_maintenance timestamp with time zone,
  insurance_company character varying,
  insurance_policy_number character varying,
  insurance_expiry timestamp with time zone,
  current_location character varying,
  usage_area character varying,
  daily_rate numeric,
  operating_days character varying,
  departure_time time without time zone,
  max_return_time time without time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid,
  deleted_at timestamp with time zone,
  CONSTRAINT vehicles_pkey PRIMARY KEY (id),
  CONSTRAINT vehicles_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id),
  CONSTRAINT vehicles_driver_id_fkey FOREIGN KEY (driver_id) REFERENCES public.drivers(id),
  CONSTRAINT vehicles_agency_id_fkey FOREIGN KEY (agency_id) REFERENCES public.agencies(id)
);